# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\gitwork\jiucai\ui\fund.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fund_view(object):
    def setupUi(self, fund_view):
        fund_view.setObjectName("fund_view")
        fund_view.resize(335, 334)
        fund_view.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.calendarWidget = QtWidgets.QCalendarWidget(fund_view)
        self.calendarWidget.setGeometry(QtCore.QRect(40, 50, 248, 197))
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton = QtWidgets.QPushButton(fund_view)
        self.pushButton.setGeometry(QtCore.QRect(30, 280, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(fund_view)
        self.pushButton.clicked.connect(fund_view.close)
        QtCore.QMetaObject.connectSlotsByName(fund_view)

    def retranslateUi(self, fund_view):
        _translate = QtCore.QCoreApplication.translate
        fund_view.setWindowTitle(_translate("fund_view", "Form"))
        self.pushButton.setText(_translate("fund_view", "关闭"))
