# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\gitwork\jiucai\ui\log.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_view(object):
    def setupUi(self, log_view):
        log_view.setObjectName("log_view")
        log_view.resize(297, 441)
        self.textBrowser = QtWidgets.QTextBrowser(log_view)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 291, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(log_view)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(log_view)
        self.radioButton.setGeometry(QtCore.QRect(90, 10, 89, 16))
        self.radioButton.setObjectName("radioButton")
        self.line = QtWidgets.QFrame(log_view)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setBaseSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setAutoFillBackground(True)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(20)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")

        self.retranslateUi(log_view)
        QtCore.QMetaObject.connectSlotsByName(log_view)

    def retranslateUi(self, log_view):
        _translate = QtCore.QCoreApplication.translate
        log_view.setWindowTitle(_translate("log_view", "log"))
        self.pushButton.setText(_translate("log_view", "保存"))
        self.radioButton.setText(_translate("log_view", "自动追踪"))
