# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\gitwork\jiucai\ui\log.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_view(object):
    def setupUi(self, log_view):
        log_view.setObjectName("log_view")
        log_view.resize(293, 441)
        self.textBrowser = QtWidgets.QTextBrowser(log_view)
        self.textBrowser.setGeometry(QtCore.QRect(0, 60, 291, 381))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(log_view)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(log_view)
        self.radioButton.setGeometry(QtCore.QRect(120, 10, 89, 16))
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(log_view)
        QtCore.QMetaObject.connectSlotsByName(log_view)

    def retranslateUi(self, log_view):
        _translate = QtCore.QCoreApplication.translate
        log_view.setWindowTitle(_translate("log_view", "log"))
        self.pushButton.setText(_translate("log_view", "保存"))
        self.radioButton.setText(_translate("log_view", "自动追踪"))
