# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\gitwork\jiucai\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.memu_tree = QtWidgets.QTreeWidget(self.centralwidget)
        self.memu_tree.setGeometry(QtCore.QRect(0, 10, 131, 541))
        self.memu_tree.setObjectName("memu_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.memu_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.memu_tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.memu_tree)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 50, 821, 491))
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_load_config = QtWidgets.QAction(MainWindow)
        self.action_load_config.setObjectName("action_load_config")
        self.action_modiy_config = QtWidgets.QAction(MainWindow)
        self.action_modiy_config.setObjectName("action_modiy_config")
        self.menu_2.addAction(self.action_load_config)
        self.menu_2.addAction(self.action_modiy_config)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.memu_tree.headerItem().setText(0, _translate("MainWindow", "目录节点"))
        __sortingEnabled = self.memu_tree.isSortingEnabled()
        self.memu_tree.setSortingEnabled(False)
        self.memu_tree.topLevelItem(0).setText(0, _translate("MainWindow", "爬虫"))
        self.memu_tree.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "基金爬虫"))
        self.memu_tree.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "指数爬虫"))
        self.memu_tree.topLevelItem(1).setText(0, _translate("MainWindow", "数据分析"))
        self.memu_tree.topLevelItem(2).setText(0, _translate("MainWindow", "数据分析2"))
        self.memu_tree.setSortingEnabled(__sortingEnabled)
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "配置"))
        self.action_load_config.setText(_translate("MainWindow", "载入配置"))
        self.action_modiy_config.setText(_translate("MainWindow", "修改配置"))
