# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\gitwork\jiucai\ui\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(640, 480)
        Test.setToolTipDuration(0)
        Test.setAutoFillBackground(True)
        Test.setStyleSheet("background-color{\n"
"rgb(85, 170, 127)\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Test)
        self.pushButton.setGeometry(QtCore.QRect(80, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Test)
        self.lineEdit.setGeometry(QtCore.QRect(80, 180, 113, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Test)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "Form"))
        self.pushButton.setText(_translate("Test", "测试log"))
