# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\gitwork\jiucai\client\ui\config.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config_dialog(object):
    def setupUi(self, config_dialog):
        config_dialog.setObjectName("config_dialog")
        config_dialog.resize(248, 363)
        config_dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        config_dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        self.widget = QtWidgets.QWidget(config_dialog)
        self.widget.setGeometry(QtCore.QRect(22, 33, 181, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.addr_label = QtWidgets.QLabel(self.widget)
        self.addr_label.setObjectName("addr_label")
        self.gridLayout.addWidget(self.addr_label, 0, 0, 1, 1)
        self.addrEdit = QtWidgets.QLineEdit(self.widget)
        self.addrEdit.setMaxLength(15)
        self.addrEdit.setObjectName("addrEdit")
        self.gridLayout.addWidget(self.addrEdit, 0, 1, 1, 1)
        self.port_label = QtWidgets.QLabel(self.widget)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 1, 0, 1, 1)
        self.portEdit = QtWidgets.QLineEdit(self.widget)
        self.portEdit.setInputMethodHints(QtCore.Qt.ImhPreferLowercase)
        self.portEdit.setObjectName("portEdit")
        self.gridLayout.addWidget(self.portEdit, 1, 1, 1, 1)
        self.account_label = QtWidgets.QLabel(self.widget)
        self.account_label.setObjectName("account_label")
        self.gridLayout.addWidget(self.account_label, 2, 0, 1, 1)
        self.accountEdit = QtWidgets.QLineEdit(self.widget)
        self.accountEdit.setMaxLength(20)
        self.accountEdit.setObjectName("accountEdit")
        self.gridLayout.addWidget(self.accountEdit, 2, 1, 1, 1)
        self.password_label = QtWidgets.QLabel(self.widget)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 3, 0, 1, 1)
        self.passwordEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordEdit.setMaxLength(20)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SaveButton = QtWidgets.QPushButton(self.widget)
        self.SaveButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SaveButton.setAutoFillBackground(False)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)
        self.CancelButton = QtWidgets.QPushButton(self.widget)
        self.CancelButton.setMinimumSize(QtCore.QSize(0, 23))
        self.CancelButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CancelButton.setStyleSheet("")
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(config_dialog)
        QtCore.QMetaObject.connectSlotsByName(config_dialog)

    def retranslateUi(self, config_dialog):
        _translate = QtCore.QCoreApplication.translate
        config_dialog.setWindowTitle(_translate("config_dialog", "配置"))
        self.addr_label.setText(_translate("config_dialog", "数据库地址"))
        self.port_label.setText(_translate("config_dialog", "端口"))
        self.account_label.setText(_translate("config_dialog", "账号"))
        self.password_label.setText(_translate("config_dialog", "密码"))
        self.SaveButton.setText(_translate("config_dialog", "保存"))
        self.CancelButton.setText(_translate("config_dialog", "取消"))
