# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\gitwork\jiucai\ui\log.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_view(object):
    def setupUi(self, log_view):
        log_view.setObjectName("log_view")
        log_view.resize(297, 441)
        self.textBrowser = QtWidgets.QTextBrowser(log_view)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 291, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(log_view)
        self.widget.setGeometry(QtCore.QRect(0, 0, 130, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)

        self.retranslateUi(log_view)
        QtCore.QMetaObject.connectSlotsByName(log_view)

    def retranslateUi(self, log_view):
        _translate = QtCore.QCoreApplication.translate
        log_view.setWindowTitle(_translate("log_view", "log"))
        self.pushButton.setText(_translate("log_view", "保存"))
        self.checkBox.setText(_translate("log_view", "跟踪"))
